Create basic classes for working with VK API
tsivarev/vk-php-sdk pull request #1
Opened 2017-12-28 15:38 UTC by erokhinav

Develop Client and Response, add base classes for Exceptions

2017-12-29 10:13 UTC, tsivarev requested changes

2017-12-29 10:13 UTC, tsivarev commented on src/VK/VKApiException.php
> +    public function get_error_code()
getErrorCode

2017-12-29 10:13 UTC, tsivarev commented on src/VK/VKClient.php
> +require_once ('VKResponse.php');
Это делается через импорт классов

2017-12-29 10:13 UTC, tsivarev commented on src/VK/VKClient.php
> +require_once ('VKResponse.php');
Т.е. use

2017-12-29 10:13 UTC, tsivarev commented on src/VK/VKClient.php
> +    protected $api_version = "5.69";
Давай использовать везде '

2017-12-29 10:13 UTC, tsivarev commented on src/VK/VKClient.php
> +    public function request($method, $params, $access_token)
Сделай params по умолчанию array()

2017-12-29 10:13 UTC, tsivarev commented on src/VK/VKClient.php
> +            CURLOPT_CONNECTTIMEOUT => 10,
Константа

2018-01-09 13:06 UTC, erokhinav commented on src/VK/Exceptions/VKApiException.php
> +     * @var string|boolean The error code.
phpdoc

2018-01-09 13:06 UTC, erokhinav commented on src/VK/VKClient.php
> +    const CONNECT_TIME_OUT = 10;
CONNECTION_TIMEOUT

2018-01-09 13:06 UTC, erokhinav commented on src/VK/VKClient.php
> +        $params['v'] = $this->api_version;
Константы

2018-01-09 13:06 UTC, erokhinav commented on src/VK/VKClient.php
> +    public function request($method, $params = array(), $access_token) {
access_token вторым аргументом

2018-01-09 13:06 UTC, erokhinav commented on src/VK/VKResponse.php
> +        $this->thrown_exception = new VKApiException($this->decoded_body['error']['error_code'],
error_code и error_msg в константы

2018-01-09 13:53 UTC, merged