Fixed missing getAccessToken function
tsivarev/vk-php-sdk pull request #11
Opened 2018-02-12 09:59 UTC by unvir

2018-02-15 15:41 UTC, tsivarev requested changes

2018-02-15 15:41 UTC, tsivarev commented on src/VK/Exceptions/Api/ApiAccessCheckinException.php
> +		parent::__construct(191, 'Access to checkins denied', $message);
отступы поехали

2018-02-16 06:13 UTC, tsivarev requested changes

2018-02-16 06:13 UTC, tsivarev commented on src/VK/Exceptions/Api/ApiAccessAlbumException.php
> +{
перенос не нужен

2018-02-16 06:13 UTC, tsivarev commented on src/VK/Exceptions/Api/ApiAccessAlbumException.php
> +    public function __construct($message)
перенос не нужен

2018-02-16 06:13 UTC, tsivarev commented on src/VK/Exceptions/Api/ExceptionMapper.php
> +                throw new Exception('Internal error');
VKApiException('Unknown error');

2018-02-16 13:41 UTC, tsivarev requested changes

2018-02-16 13:41 UTC, tsivarev commented on scripts/GenerateActions.php
> +            '@throws VKClientException in case of error on the Api side',
На самом деле тут наоборот "VKClientException in case of network error"

2018-02-16 13:41 UTC, tsivarev commented on src/VK/Actions/Account.php
> -     * Account constructor.
А чего исчезло?

2018-02-16 13:41 UTC, tsivarev commented on src/VK/Actions/Account.php
> +method.
Надо бы поправить

2018-02-16 13:41 UTC, tsivarev commented on src/VK/Exceptions/Api/VKApiException.php
> +    public function __construct(int $code, string $description, string $message)
не нужно переносить

2018-02-16 13:41 UTC, tsivarev commented on src/VK/Exceptions/Api/ApiSignatureException.php
> -    /**
вернуть

2018-02-16 13:41 UTC, tsivarev commented on src/VK/Client/VKApiClient.php
> +    public function __construct(string $api_version = self::VK_API_VERSION) {
вернуть

2018-02-16 13:41 UTC, tsivarev commented on src/VK/Actions/Wall.php
> +     * @throws ApiWallAccessPostException
взять описание ошибки, если оно есть

2018-02-16 13:42 UTC, unvir commented on src/VK/Actions/Account.php
> -     * Account constructor.
Это было вручную сгенерировано

2018-02-20 06:13 UTC, tsivarev approved these changes

2018-02-20 06:13 UTC, merged