Implemented Callback API & Implicit flow auth
tsivarev/vk-php-sdk pull request #9
Opened 2018-02-07 09:50 UTC by unvir

2018-02-07 12:08 UTC, tsivarev requested changes

2018-02-07 12:08 UTC, tsivarev commented on src/VK/OAuth/VKOAuth.php
> +    public function authorize(int $authorize_method = OAuthFlow::AUTHORIZATION_CODE, int $client_id, string $redirect_uri,
А чему authorize_method не string?

2018-02-07 12:08 UTC, tsivarev commented on src/VK/OAuth/VKOAuth.php
> +        } else if($authorize_method == OAuthFlow::IMPLICIT) {
пробел после if

2018-02-07 12:08 UTC, tsivarev commented on src/VK/OAuth/VKOAuth.php
> +            static::API_PARAM_GROUP_IDS => join(',', $group_ids),
лучше implode

2018-02-07 12:08 UTC, tsivarev commented on src/VK/CallbackApi/CallbackApi.php
> +class CallbackApi extends CallbackApiHandler {
Лучше назвать CallbackApiServerHandler и поместить в namespace VK\CallbackApi\Server

2018-02-07 12:11 UTC, unvir commented on src/VK/OAuth/VKOAuth.php
> +    public function authorize(int $authorize_method = OAuthFlow::AUTHORIZATION_CODE, int $client_id, string $redirect_uri,
Потому что OAuthFlow состоит из целочисленных констант AUTH_CODE = 0 и IMPLICIT = 1. Мне кажется, нет смысла давать им значения в виде string

2018-02-07 12:52 UTC, tsivarev requested changes

2018-02-07 12:52 UTC, tsivarev commented on README.md
> +class myCallback extends CallbackApiServerHandler {
CallbackServer

2018-02-07 12:52 UTC, tsivarev commented on src/VK/CallbackApi/Server/CallbackApiServerHandler.php
> +class CallbackApiServerHandler extends CallbackApiHandler {
abstract

2018-02-07 12:58 UTC, tsivarev requested changes

2018-02-07 12:58 UTC, tsivarev commented on README.md
> +    protected function confirmation(int $group_id, string $token, ?string $secret) {
А что такое token?

2018-02-07 12:58 UTC, tsivarev commented on README.md
> +        MyLog.send('I`m got new message');
лучше удалить эту строчку

2018-02-08 12:21 UTC, tsivarev approved these changes

2018-02-08 12:22 UTC, merged